### ISSUE TITLE
"anonymous" is spelled incorrectly in the API

### ISSUE THREAD

**Issue by ottumm** [amcgee/remjs#2]
``annonymous_signup``, ``annonymous_permissions``, and the ``annonymous`` array all spell "anonymous" incorrectly. I'd like to fix this, but am worried about breaking changes, so perhaps it will need to accept both.

**Comment by amcgee** [comment]
We should be able to use a reasonable semantic version number for this change.  Plus the only thing using it is Strato, AFAIK
